
services:
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: launchpad-nextjs
    ports:
      - "3120:3005"
    restart: always
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=3005
    env_file:
      - .env